language: php

matrix:
  include:
    - php: 5.5.9
      dist: trusty
    - php: 5.5
      dist: trusty
    - php: 5.6
      dist: xenial
    - php: 7.0
      dist: xenial
    - php: 7.1
      dist: xenial
    - php: 7.2
      dist: xenial
    - php: 7.3
      dist: xenial
    - php: hhvm-3.18
      dist: trusty

before_install:
  - if [[ $TRAVIS_PHP_VERSION = "hhvm-3.18" ]]; then echo 'hhvm.jit = false' >> /etc/hhvm/php.ini ; fi

install: travis_retry composer install --no-suggest --prefer-dist -n -o

script: vendor/bin/phpunit
