language: php

sudo: false

matrix:
  include:
    - php: 5.5.9
    - php: 5.5
    - php: 5.6
    - php: 7.0
    - php: hhvm

install: travis_retry composer install --no-interaction --prefer-source

script: vendor/bin/phpunit
